### PR TITLE
navbar change + folder renaming

### PR DESCRIPTION
**Pull request by shivam-51**

### CODE REVIEW

**Comment by shivam-51** [comment]
- git fetch origin pull/63/head:shivam
- git checkout shivam
- npm run serve

to view these changes locally

**Review by BAAHUBALI7781 — COMMENTED** [review]
It is looking good! I had two changes in mind:
1) The slideshow of images in the home page: It is very close to the navbar so we can have some margin between them.
2) In the dropdown menu in navbar, there is no boundary of seperation between the 3 columns. I think the horizontal lines between them will give it a better button type of look.
Rests everything is great👍

**Comment by shivam-51** [comment]
> It is looking good! I had two changes in mind:
> 
> 1. The slideshow of images in the home page: It is very close to the navbar so we can have some margin between them.
> 2. In the dropdown menu in navbar, there is no boundary of seperation between the 3 columns. I think the horizontal lines between them will give it a better button type of look.
>    Rests everything is great+1

My change had nothing as such with the navbar it was rather to hide Sign in when you are in the Sign in page and to hide Sign up when you are in the sign up page.
Your points are noteworthy, Send a PR to resolve them soon :wink:

**Comment by shivam-51** [comment]
No idea why @praneetha3108 is not reviewing the patches, I have requested her multiple times.
Will have to move forward

**Comment by BAAHUBALI7781** [comment]
Yeah sure! I will be happy to contribute.

**Comment by aditya2610** [comment]
As in the slide,we can add one feature like clicking on the image and it
will get directed to the IIEST main page and same for Socit IT.
Rest things are all cool.

**Pull request merged**
